import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Tłumaczenia
const translations: Record<Language, any> = {
  pl: {
    common: {
      welcome: "Witamy",
      login: "Zaloguj się",
      register: "Zarejestruj się",
      logout: "Wyloguj",
      logOut: "Wyloguj się",
      home: "Strona główna",
      profile: "Profil",
      admin: "Panel admina",
      settings: "Ustawienia",
      language: "Język",
      balance: "Saldo",
      loading: "Ładowanie...",
      error: "Błąd",
      success: "Sukces",
      cancel: "Anuluj",
      confirm: "Potwierdź",
      back: "Wstecz",
      play: "Graj",
      bet: "Zakład",
      spin: "Zakręć",
      deal: "Rozdaj",
      hit: "Dobierz",
      stand: "Pasuj",
      double: "Podwój",
      split: "Rozdziel",
      save: "Zapisz",
      close: "Zamknij",
      deposit: "Wpłata",
      withdraw: "Wypłata",
      history: "Historia",
      characters: "znaków",
      you: "Ty"
    },
    nav: {
      games: "Gry",
      slots: "Automaty",
      roulette: "Ruletka",
      blackjack: "Blackjack",
      poker: "Poker"
    },
    auth: {
      username: "Nazwa użytkownika",
      email: "Email",
      password: "Hasło",
      confirmPassword: "Potwierdź hasło",
      forgotPassword: "Zapomniałeś hasła?",
      resetPassword: "Resetuj hasło",
      noAccount: "Nie masz konta?",
      hasAccount: "Masz już konto?",
      loginSuccess: "Zalogowano pomyślnie",
      registerSuccess: "Rejestracja zakończona",
      name: "Imię",
      surname: "Nazwisko",
      signUp: "Zarejestruj się",
      enterEmail: "Wpisz email",
      enterPassword: "Wpisz hasło",
      confirmYourPassword: "Potwierdź hasło",
      invalidEmail: "Nieprawidłowy adres email",
      passwordMismatch: "Hasła się nie zgadzają",
      passwordTooShort: "Hasło musi mieć co najmniej 6 znaków",
      userExists: "Użytkownik o tym emailu już istnieje",
      invalidCredentials: "Nieprawidłowy email lub hasło",
      confirmEmail: "Potwierdź adres email przed zalogowaniem"
    },
    games: {
      blackjack: {
        title: "Blackjack",
        description: "Pobij krupiera i zdobądź 21!",
        selectMode: "Wybierz tryb gry",
        classicBlackjack: "Classic Blackjack",
        classicDescription: "Klasyczny blackjack. Graj sam przeciwko krupierowi i doskonał swoje umiejętności.",
        playSolo: "Graj Solo",
        multiplayer21: "Multiplayer 21",
        multiplayerDescription: "Prawdziwe emocje przy stole! Dołącz do innych graczy i pokonaj krupiera razem.",
        joinTable: "Dołącz do Stołu",
        singlePlayer: "Gra jednoosobowa",
        multiplayer: "Gra wieloosobowa",
        lobby: "Lobby",
        dealer: "Krupier",
        dealerScore: "Wynik krupiera",
        dealerCards: "Karty Krupiera",
        yourScore: "Twój wynik",
        betAmount: "Kwota zakładu",
        winAmount: "Wygrana",
        dealCards: "ROZDAJ KARTY",
        dealing: "ROZDAWANIE...",
        hit: "DOBIERZ",
        stand: "PASUJ",
        double: "PODWÓJ",
        win: "WYGRANA!",
        blackjack: "BLACKJACK!",
        lose: "PRZEGRANA",
        push: "REMIS",
        waiting: "Oczekiwanie...",
        dealToStart: "Rozdaj karty, aby zagrać",
        currentBet: "Stawka: {{bet}} PLN",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        gameError: "Błąd podczas rozpoczynania gry",
        hitError: "Błąd podczas dobierania karty",
        standError: "Błąd podczas pasowania",
        doubleError: "Błąd podczas podwajania",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking",
        connecting: "Łączenie z kasynem...",
        enteringTable: "Wchodzenie do stołu...",
        tableLabel: "Stół",
        stageLabel: "Etap",
        leaveTable: "Wyjdź",
        yourTurn: "Twój ruch",
        historyTitle: "Historia gry",
        tableChat: "Czat stołu",
        startChat: "Rozpocznij rozmowę...",
        chatPlaceholder: "Napisz wiadomość...",
        placeBet: "Postaw"
      },
      roulettePage: {
        title: "Ruletka",
        placeBet: "Postaw zakład",
        selectNumber: "Wybierz numer",
        selectColor: "Wybierz kolor",
        red: "Czerwone",
        black: "Czarne",
        even: "Parzyste",
        odd: "Nieparzyste"
      },
      poker: {
        title: "Poker",
        description: "Zagraj w Texas Hold'em",
        selectMode: "Wybierz tryb gry",
        royalPoker: "Royal Poker",
        royalDescription: "Trening czyni mistrza. Graj przeciwko krupierowi i doskonał swoje umiejętności.",
        playSolo: "Graj Solo",
        texasHoldem: "Texas Hold'em",
        texasDescription: "Prawdziwe emocje przy stole! Dołącz do innych graczy i walcz o najwyższe stawki.",
        joinTable: "Dołącz do Stołu",
        singlePlayer: "Gra jednoosobowa",
        multiplayer: "Gra wieloosobowa",
        lobby: "Lobby",
        fold: "Pasuj",
        call: "Sprawdź",
        raise: "Podbij",
        check: "Czekaj",
        allIn: "All-in",
        yourCards: "Twoje karty",
        communityCards: "Karty wspólne",
        pot: "Pula",
        turn: "Twoja kolej",
        bet: "Zakład",
        waiting: "Oczekiwanie...",
        dealToStart: "Rozdaj karty, aby zagrać",
        dealCards: "ROZDAJ KARTY",
        dealing: "TASOWANIE...",
        nextRound: "NASTĘPNE ROZDANIE",
        selectCards: "Wybierz karty do wymiany",
        selectedCards: "Wybrano do wymiany: {{count}}",
        exchange: "WYMIEŃ KARTY",
        win: "WYGRANA!",
        lose: "PRZEGRANA",
        gameStartError: "Błąd startu",
        gameExchangeError: "Błąd wymiany",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking",
        connecting: "Łączenie z kasynem...",
        enteringTable: "Wchodzenie do stołu...",
        tableLabel: "Stół",
        stageLabel: "Etap",
        leaveTable: "Wyjdź",
        historyTitle: "Historia gry",
        tableChat: "Czat stołu",
        startChat: "Rozpocznij rozmowę...",
        chatPlaceholder: "Napisz wiadomość...",
        folded: "Pas",
        youFolded: "Spasowałeś"
      },
      slots: {
        title: "Automaty",
        description: "Zagraj w automaty i wygraj!",
        spin: "ZAKRĘĆ",
        bet: "Zakład",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        gameError: "Błąd podczas gry",
        win: "WYGRANA!",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      },
      roulette: {
        title: "Ruletka",
        description: "Postaw żetony i zakręć!",
        placeBet: "Postaw żeton",
        selectNumber: "Wybierz numer",
        selectColor: "Wybierz kolor",
        red: "Czerwone",
        black: "Czarne",
        even: "Parzyste",
        odd: "Nieparzyste",
        low: "Niskie",
        high: "Wysokie",
        bet: "Zakład",
        spin: "ZAKRĘĆ",
        gameError: "Błąd gry",
        win: "WYGRANA!",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      }
    },
    profile: {
      title: "Twój profil",
      userInfo: "Informacje o użytkowniku",
      statistics: "Statystyki",
      gamesPlayed: "Rozegrane gry",
      totalWins: "Wygrane",
      totalLosses: "Przegrane",
      winRate: "Procent wygranych",
      missions: "Misje",
      dailyMissions: "Misje dzienne",
      dailyRewards: "Nagrody dzienne",
      streak: "Seria",
      days: "dni",
      claimReward: "Odbierz nagrodę",
      nextRewardIn: "Następna nagroda za",
      name: "Imię",
      surname: "Nazwisko",
      email: "Email",
      accountStatus: "Status konta",
      vipStatus: "Status VIP",
      isVip: "Tak, jestem VIP",
      notVip: "Nie jestem VIP",
      changePassword: "Zmień hasło",
      currentPassword: "Aktualne hasło",
      newPassword: "Nowe hasło",
      confirmNewPassword: "Potwierdź nowe hasło",
      security: "Bezpieczeństwo",
      changePasswordTitle: "Zmiana hasła",
      changePasswordButton: "ZMIEŃ HASŁO",
      deleteAccountButton: "USUŃ KONTO",
      deleteAccount: "Usuń konto",
      deleteAccountTitle: "Usuń konto",
      deleteAccountWarning: "⚠️ Ostrzeżenie!",
      deleteAccountText: "Ta operacja jest nieodwracalna. Wszystkie Twoje dane, historia gier i saldo zostaną permanentnie usunięte.",
      deleteAccountConfirm: "Czy na pewno chcesz usunąć swoje konto?",
      enterPasswordToConfirm: "Wpisz swoje hasło aby potwierdzić",
      allFieldsRequired: "Wszystkie pola są wymagane",
      passwordMinLength: "Nowe hasło musi mieć co najmniej 6 znaków",
      passwordNotMatching: "Nowe hasła nie są zgodne",
      passwordChangedSuccess: "Hasło zostało zmienione pomyślnie",
      passwordChanged: "Hasło zostało zmienione",
      passwordChangeError: "Nie udało się zmienić hasła",
      invalidPassword: "Nieprawidłowe hasło",
      deleteAccountError: "Nie udało się usunąć konta",
      deleteAccountSuccess: "Konto zostało pomyślnie usunięte",
      keepAccount: "Nie, zachowaj konto",
      confirmDeleteAccount: "Tak, usuń konto",
      cancel: "Anuluj",
      transactions: "Transakcje",
      gameHistory: "Historia gier",
      noTransactions: "Brak transakcji",
      noGameHistory: "Brak historii gier",
      loadMore: "Wczytaj więcej",
      depositFunds: "Wpłać środki",
      withdrawFunds: "Wypłać środki",
      enterAmount: "Wpisz kwotę",
      minimumAmount: "Minimalnie",
      maximumAmount: "Maksymalnie",
      processingPayment: "Przetwarzanie płatności...",
      balance: "Saldo",
      type: "Typ",
      outcome: "Wynik",
      winAmount: "Wygrana",
      date: "Data",
      win: "Wygrana",
      lose: "Przegrana"
    },
    missions: {
      title: "Misje",
      daily: "Dzienne",
      completed: "Ukończone",
      inProgress: "W trakcie",
      reward: "Nagroda",
      progress: "Postęp",
      claim: "Odbierz",
      claimed: "Odebrane",
      complete: "Ukończ",
      completionReward: "Nagroda za ukończenie"
    },
    admin: {
      title: "Panel Administratora",
      users: "Użytkownicy",
      userManagement: "Zarządzanie użytkownikami",
      email: "Email",
      name: "Imię",
      surname: "Nazwisko",
      balance: "Saldo",
      isVip: "VIP",
      isActive: "Aktywny",
      actions: "Akcje",
      edit: "Edytuj",
      delete: "Usuń",
      ban: "Zablokuj",
      unban: "Odblokuj",
      makeVip: "Uczyń VIP",
      removeVip: "Usuń VIP",
      noUsers: "Brak użytkowników",
      firstName: "Imię",
      lastName: "Nazwisko",
      active: "Aktywni",
      vip: "VIP",
      searchPlaceholder: "🔍 Szukaj użytkownika...",
      id: "ID",
      status: "Status",
      noPermissions: "Brak uprawnień administratora",
      serverError: "Błąd serwera",
      loading: "⏳ Ładowanie...",
      error: "❌ Błąd",
      confirmDelete: "Czy na pewno chcesz usunąć tego użytkownika?",
      userDeleted: "Użytkownik usunięty",
      deleteError: "Błąd podczas usuwania",
      updateBalance: "Zmień balans",
      enterBalance: "Podaj nowy balans:",
      balanceUpdated: "Balans zaktualizowany",
      updateError: "Błąd podczas aktualizacji balansu",
      previous: "← Poprzednia",
      next: "Następna →",
      page: "Strona",
      of: "/"
    },
    lobby: {
      title: "Lobby",
      createTable: "Utwórz stół",
      joinTable: "Dołącz do stołu",
      availableTables: "Dostępne stoły",
      tableName: "Nazwa stołu",
      minBet: "Minimalny zakład",
      maxBet: "Maksymalny zakład",
      maxPlayers: "Maks. graczy",
      currentPlayers: "Aktualnie graczy",
      waiting: "Oczekiwanie...",
      players: "Gracze",
      status: "Status",
      startGame: "Zacznij grę",
      joinGame: "Dołącz do gry",
      full: "Pełne",
      inProgress: "Trwa gra",
      selectTable: "Wybierz stół i zacznij grać",
      playNow: "Zagraj teraz",
      minBuyIn: "Min. wejście",
      loadingTables: "Ładowanie stołów..."
    },
    validation: {
      required: "To pole jest wymagane",
      invalidEmail: "Nieprawidłowy adres email",
      passwordTooShort: "Hasło musi mieć co najmniej 6 znaków",
      passwordMismatch: "Hasła się nie zgadzają",
      amountInvalid: "Nieprawidłowa kwota",
      amountTooSmall: "Kwota za mała",
      insufficientBalance: "Niewystarczające saldo"
    },
    help: {
      help: "Pomoc",
      howToPlay: "Jak grać?",
      rules: "Zasady gry",
      actions: "Dostępne akcje",
      tips: "Porady",
      // Poker
      pokerTitle: "Texas Hold'em Poker",
      pokerDesc: "Gra karciana, w której celem jest zdobycie najlepszego układu 5 kart z 7 dostępnych (2 własne + 5 wspólnych).",
      goalOfGame: "Cel gry",
      winPot: "Wygraj pulę mając najlepszy układ kart lub zmuszając wszystkich przeciwników do spasowania.",
      ante: "Ante",
      anteDesc: "Na początku każdego rozdania każdy gracz wpłaca ante (100$) do puli startowej.",
      gameStages: "Etapy gry",
      stagesDesc: "PreFlop (2 karty własne) → Flop (3 karty wspólne) → Turn (4. karta) → River (5. karta) → Showdown (porównanie układów).",
      cardHands: "Układy kart",
      handsDesc: "Od najsłabszego: Wysoka karta, Para, Dwie pary, Trójka, Strit, Kolor, Full, Kareta, Poker, Poker królewski.",
      fold: "PAS (Fold)",
      foldDesc: "Rezygnujesz z rozdania i tracisz wpłacone żetony. Użyj gdy masz słabe karty.",
      check: "CZEKAJ (Check)",
      checkDesc: "Przechodzisz dalej bez wpłacania, gdy nikt nie podniósł stawki.",
      call: "SPRAWDŹ (Call)",
      callDesc: "Wyrównujesz aktualną stawkę przeciwnika, aby zostać w grze.",
      raise: "PODBIJ (Raise)",
      raiseDesc: "Podnosisz stawkę - musisz podbić co najmniej do aktualnego minimum + 1$. Wpisz kwotę i kliknij PODBIJ.",
      allIn: "ALL-IN",
      allInDesc: "Stawiasz wszystkie swoje żetony. Automatyczne gdy podbijasz więcej niż masz.",
      observeOpponents: "Obserwuj zachowanie przeciwników - częste podbijanie może oznaczać silną rękę.",
      dontFearFold: "Nie bój się pasować przy słabych kartach - oszczędność żetonów to też strategia.",
      positionMatters: "Pozycja ma znaczenie - grając jako ostatni masz więcej informacji.",
      manageBankroll: "Zarządzaj swoim bankrollem - nie ryzykuj wszystkiego na jedną rękę.",
      // Blackjack
      blackjackTitle: "Blackjack (Oczko)",
      blackjackDesc: "Klasyczna gra karciana. Zbierz karty o wartości jak najbliższej 21, ale nie przekrocz tej liczby!",
      beatDealer: "Pokonaj krupiera mając więcej punktów (max 21). Przekroczenie 21 = przegrana.",
      cardValues: "Wartości kart",
      valuesDesc: "2-10 = wartość nominalna, J/Q/K = 10 punktów, As = 1 lub 11 punktów.",
      blackjack: "Blackjack",

      dealer: "Krupier",
      dealerDesc: "Krupier musi dobierać do 16 i stać na 17+.",
      hit: "DOBIERZ (Hit)",
      hitDesc: "Dobierz kolejną kartę. Ryzykujesz przekroczenie 21!",
      stand: "STÓJ (Stand)",
      standDesc: "Zatrzymaj obecną sumę i pozwól krupierowi grać.",
      double: "PODWÓJ (Double)",
      doubleDesc: "Podwój zakład i dobierz dokładnie jedną kartę (dostępne tylko na początku).",
      placeBet: "POSTAW (Bet)",
      placeBetDesc: "Ustaw wysokość zakładu przed rozdaniem kart.",
      alwaysDouble11: "Przy sumie 11 zawsze podwajaj (jeśli możesz).",
      standAt17: "Stój przy 17+ - ryzyko przekroczenia 21 jest zbyt wysokie.",
      hitAt11Less: "Dobieraj przy sumie 11 lub mniej - nie możesz przegrać.",
      watchDealerCard: "Obserwuj odkrytą kartę krupiera - jeśli ma 6 lub mniej, częściej przekroczy 21.",
      // Roulette
      rouletteTitle: "Ruletka",
      rouletteDesc: "Klasyczna gra kasynowa - postaw na numer, kolor lub zakres i czekaj na wynik!",
      predictNumber: "Przewiduj, na którym numerze zatrzyma się kulka. Wygrana zależy od typu zakładu.",
      numbers: "Numery",
      numbersDesc: "Ruletka europejska ma numery 0-36. Zero jest zielone, reszta to czerwone i czarne.",
      payouts: "Wypłaty",
      payoutsDesc: "Numer: 35:1 | Kolor: 1:1 | Parzyste/Nieparzyste: 1:1 | Połowa (1-18/19-36): 1:1",
      selectChip: "Wybierz żeton",
      selectChipDesc: "Kliknij na żeton (10, 50, 100 lub 500) aby wybrać wartość zakładu.",
      placeBetRoulette: "Postaw zakład",
      placeBetRouletteDesc: "Kliknij na stole w miejsce gdzie chcesz postawić - numer, kolor, parzyste itp.",
      spin: "SPIN",
      spinDesc: "Zakręć kołem ruletki i czekaj na wynik!",
      clearBets: "Wyczyść zakłady",
      clearBetsDesc: "Usuń wszystkie postawione zakłady przed spinem.",
      outsideBets: "Zakłady zewnętrzne (kolor, parzyste) mają większą szansę wygranej, ale mniejszą wypłatę.",
      multipleBeats: "Możesz postawić wiele zakładów naraz - strategia pokrycia wielu numerów.",
      zeroHouseEdge: "Zero daje przewagę kasynu - unikaj zakładów tylko na zero.",
      setBettingLimit: "Ustal limit zakładów i trzymaj się go!",
      // Slots
      slotsTitle: "Automaty (Slots)",
      slotsDesc: "Klasyczne jednorękie bandyty - pociągnij za dźwignię i wygraj!",
      lineUpSymbols: "Ułóż 3 takie same symbole w linii, aby wygrać. Różne symbole dają różne mnożniki.",
      symbols: "Symbole",
      symbolsDesc: "🍋 Cytryna (2x) | 🍒 Wiśnie (3x) | 🍇 Winogrona (5x) | 🔔 Dzwonek (10x) | ☘️ Koniczyna (15x) | 7️⃣ Siódemka (25x) | 💎 Diament (50x)",
      winningLines: "Linie wygrywające",
      winningLinesDesc: "Wygrana następuje gdy 3 takie same symbole pojawią się w środkowym rzędzie.",
      setBet: "Ustaw zakład",
      setBetDesc: "Użyj przycisków - i + lub wpisz kwotę zakładu.",
      pull: "POCIĄGNIJ / SPIN",
      pullDesc: "Kliknij dźwignię lub przycisk SPIN aby zakręcić bębnami.",
      diamondsHighest: "Diamenty dają najwyższą wygraną (50x), ale są najrzadsze.",
      sevensSecond: "Siódemki to drugi najlepszy symbol (25x stawki).",
      playResponsibly: "Graj rozsądnie - automaty są losowe, nie ma \"gorących\" maszyn.",
      setLossLimit: "Ustaw limit strat przed rozpoczęciem gry."
    }
  },
  en: {
    common: {
      welcome: "Welcome",
      login: "Log in",
      register: "Sign up",
      logout: "Log out",
      logOut: "Log out",
      home: "Home",
      profile: "Profile",
      admin: "Admin panel",
      settings: "Settings",
      language: "Language",
      balance: "Balance",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      confirm: "Confirm",
      back: "Back",
      play: "Play",
      bet: "Bet",
      spin: "Spin",
      deal: "Deal",
      hit: "Hit",
      stand: "Stand",
      double: "Double",
      split: "Split",
      save: "Save",
      close: "Close",
      deposit: "Deposit",
      withdraw: "Withdraw",
      history: "History",
      characters: "characters",
      you: "You"
    },
    nav: {
      games: "Games",
      slots: "Slots",
      roulette: "Roulette",
      blackjack: "Blackjack",
      poker: "Poker"
    },
    auth: {
      username: "Username",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      forgotPassword: "Forgot password?",
      resetPassword: "Reset password",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      loginSuccess: "Successfully logged in",
      registerSuccess: "Registration successful",
      name: "First name",
      surname: "Last name",
      signUp: "Sign up",
      enterEmail: "Enter email",
      enterPassword: "Enter password",
      confirmYourPassword: "Confirm password",
      invalidEmail: "Invalid email address",
      passwordMismatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 6 characters",
      userExists: "User with this email already exists",
      invalidCredentials: "Invalid email or password",
      confirmEmail: "Please confirm your email before logging in"
    },
    games: {
      blackjack: {
        title: "Blackjack",
        description: "Beat the dealer and get 21!",
        selectMode: "Choose game mode",
        classicBlackjack: "Classic Blackjack",
        classicDescription: "Classic blackjack. Play alone against the dealer and perfect your skills.",
        playSolo: "Play Solo",
        multiplayer21: "Multiplayer 21",
        multiplayerDescription: "Real emotions at the table! Join other players and beat the dealer together.",
        joinTable: "Join Table",
        singlePlayer: "Single player",
        multiplayer: "Multiplayer",
        lobby: "Lobby",
        dealer: "Dealer",
        dealerScore: "Dealer score",
        dealerCards: "Dealer Cards",
        yourScore: "Your score",
        betAmount: "Bet amount",
        winAmount: "Win amount",
        dealCards: "DEAL CARDS",
        dealing: "DEALING...",
        hit: "HIT",
        stand: "STAND",
        double: "DOUBLE",
        win: "WIN!",
        blackjack: "BLACKJACK!",
        lose: "LOSE",
        push: "PUSH",
        waiting: "Waiting...",
        dealToStart: "Deal cards to play",
        currentBet: "Bet: {{bet}} PLN",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        gameError: "Error starting game",
        hitError: "Error during hit",
        standError: "Error during stand",
        doubleError: "Error during double",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard",
        connecting: "Connecting to the casino...",
        enteringTable: "Entering the table...",
        tableLabel: "Table",
        stageLabel: "Stage",
        leaveTable: "Leave",
        yourTurn: "Your turn",
        historyTitle: "Game history",
        tableChat: "Table chat",
        startChat: "Start the conversation...",
        chatPlaceholder: "Write a message...",
        placeBet: "Place bet"
      },
      roulettePage: {
        title: "Roulette",
        placeBet: "Place bet",
        selectNumber: "Select number",
        selectColor: "Select color",
        red: "Red",
        black: "Black",
        even: "Even",
        odd: "Odd"
      },
      poker: {
        title: "Poker",
        description: "Play Texas Hold'em",
        selectMode: "Choose game mode",
        royalPoker: "Royal Poker",
        royalDescription: "Practice makes perfect. Play against the dealer and perfect your skills.",
        playSolo: "Play Solo",
        texasHoldem: "Texas Hold'em",
        texasDescription: "Real emotions at the table! Join other players and fight for the highest stakes.",
        joinTable: "Join Table",
        singlePlayer: "Single player",
        multiplayer: "Multiplayer",
        lobby: "Lobby",
        fold: "Fold",
        call: "Call",
        raise: "Raise",
        check: "Check",
        allIn: "All-in",
        yourCards: "Your cards",
        communityCards: "Community cards",
        pot: "Pot",
        turn: "Your turn",
        bet: "Bet",
        waiting: "Waiting...",
        dealToStart: "Deal cards to play",
        dealCards: "DEAL CARDS",
        dealing: "SHUFFLING...",
        nextRound: "NEXT ROUND",
        selectCards: "Select cards to exchange",
        selectedCards: "Selected to exchange: {{count}}",
        exchange: "EXCHANGE CARDS",
        win: "WIN!",
        lose: "LOSE",
        gameStartError: "Start error",
        gameExchangeError: "Exchange error",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard",
        connecting: "Connecting to the casino...",
        enteringTable: "Entering the table...",
        tableLabel: "Table",
        stageLabel: "Stage",
        leaveTable: "Leave",
        historyTitle: "Game history",
        tableChat: "Table chat",
        startChat: "Start the conversation...",
        chatPlaceholder: "Write a message...",
        folded: "Folded",
        youFolded: "You folded"
      },
      slots: {
        title: "Slot Machines",
        description: "Play slots and win!",
        dealCards: "SPIN",
        bet: "Bet",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        gameError: "Game error",
        win: "WIN!",
        multiplier: "x",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      },
      roulette: {
        title: "Roulette",
        description: "Place your bets and spin!",
        placeBet: "Place bet",
        selectNumber: "Select number",
        selectColor: "Select color",
        red: "Red",
        black: "Black",
        even: "Even",
        odd: "Odd",
        low: "Low",
        high: "High",
        bet: "Bet",
        spin: "SPIN",
        gameError: "Game error",
        win: "WIN!",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      }
    },
    profile: {
      title: "Your profile",
      userInfo: "User information",
      statistics: "Statistics",
      gamesPlayed: "Games played",
      totalWins: "Wins",
      totalLosses: "Losses",
      winRate: "Win rate",
      missions: "Missions",
      dailyMissions: "Daily missions",
      dailyRewards: "Daily rewards",
      streak: "Streak",
      days: "days",
      claimReward: "Claim reward",
      nextRewardIn: "Next reward in",
      name: "First name",
      surname: "Last name",
      email: "Email",
      accountStatus: "Account Status",
      vipStatus: "VIP Status",
      isVip: "Yes, I'm VIP",
      notVip: "Not VIP",
      changePassword: "Change password",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      security: "Security",
      changePasswordTitle: "Change password",
      changePasswordButton: "CHANGE PASSWORD",
      deleteAccountButton: "DELETE ACCOUNT",
      deleteAccount: "Delete account",
      deleteAccountTitle: "Delete account",
      deleteAccountWarning: "⚠️ Warning!",
      deleteAccountText: "This action is irreversible. All your data, game history and balance will be permanently deleted.",
      deleteAccountConfirm: "Are you sure you want to delete your account?",
      enterPasswordToConfirm: "Enter your password to confirm",
      allFieldsRequired: "All fields are required",
      passwordMinLength: "New password must be at least 6 characters",
      passwordNotMatching: "New passwords do not match",
      passwordChangedSuccess: "Password changed successfully",
      passwordChanged: "Password has been changed",
      passwordChangeError: "Failed to change password",
      invalidPassword: "Invalid password",
      deleteAccountError: "Failed to delete account",
      deleteAccountSuccess: "Account has been successfully deleted",
      keepAccount: "No, keep my account",
      confirmDeleteAccount: "Yes, delete my account",
      cancel: "Cancel",
      transactions: "Transactions",
      gameHistory: "Game history",
      noTransactions: "No transactions",
      noGameHistory: "No game history",
      loadMore: "Load more",
      depositFunds: "Deposit funds",
      withdrawFunds: "Withdraw funds",
      enterAmount: "Enter amount",
      minimumAmount: "Minimum",
      maximumAmount: "Maximum",
      processingPayment: "Processing payment...",
      balance: "Balance",
      type: "Type",
      outcome: "Outcome",
      winAmount: "Win amount",
      date: "Date",
      win: "Win",
      lose: "Lose"
    },
    missions: {
      title: "Missions",
      daily: "Daily",
      completed: "Completed",
      inProgress: "In progress",
      reward: "Reward",
      progress: "Progress",
      claim: "Claim",
      claimed: "Claimed",
      complete: "Complete",
      completionReward: "Completion reward"
    },
    admin: {
      title: "Admin Panel",
      users: "Users",
      userManagement: "User Management",
      email: "Email",
      name: "First name",
      surname: "Last name",
      balance: "Balance",
      isVip: "VIP",
      firstName: "First name",
      lastName: "Last name",
      active: "Active",
      vip: "VIP",
      searchPlaceholder: "🔍 Search user...",
      id: "ID",
      status: "Status",
      noPermissions: "Admin permissions required",
      serverError: "Server error",
      loading: "⏳ Loading...",
      error: "❌ Error",
      confirmDelete: "Are you sure you want to delete this user?",
      userDeleted: "User deleted",
      deleteError: "Error while deleting user",
      updateBalance: "Change balance",
      enterBalance: "Enter new balance:",
      balanceUpdated: "Balance updated",
      updateError: "Error while updating balance",
      previous: "← Previous",
      next: "Next →",
      page: "Page",
      of: "/"
    },
    lobby: {
      title: "Lobby",
      createTable: "Create table",
      joinTable: "Join table",
      availableTables: "Available tables",
      tableName: "Table name",
      minBet: "Minimum bet",
      maxBet: "Maximum bet",
      maxPlayers: "Max players",
      currentPlayers: "Current players",
      waiting: "Waiting...",
      players: "Players",
      status: "Status",
      startGame: "Start game",
      joinGame: "Join game",
      full: "Full",
      inProgress: "In progress",
      selectTable: "Choose a table and start playing",
      playNow: "Play now",
      minBuyIn: "Min. buy-in",
      loadingTables: "Loading tables..."
    },
    help: {
      help: "Help",
      howToPlay: "How to play?",
      rules: "Game rules",
      actions: "Available actions",
      tips: "Tips",
      // Poker
      pokerTitle: "Texas Hold'em Poker",
      pokerDesc: "A card game where the goal is to get the best 5-card hand from 7 available cards (2 own + 5 community).",
      goalOfGame: "Goal of the game",
      winPot: "Win the pot by having the best card hand or forcing all opponents to fold.",
      ante: "Ante",
      anteDesc: "At the beginning of each hand, each player antes ($100) to the starting pot.",
      gameStages: "Game stages",
      stagesDesc: "PreFlop (2 own cards) → Flop (3 community cards) → Turn (4th card) → River (5th card) → Showdown (compare hands).",
      cardHands: "Card hands",
      handsDesc: "From weakest to strongest: High card, Pair, Two pair, Three of a kind, Straight, Flush, Full house, Four of a kind, Straight flush, Royal flush.",
      fold: "FOLD",
      foldDesc: "You give up the hand and lose your chips. Use when you have weak cards.",
      check: "CHECK",
      checkDesc: "You proceed without betting when no one has raised.",
      call: "CALL",
      callDesc: "You match the opponent's current bet to stay in the game.",
      raise: "RAISE",
      raiseDesc: "You increase the bet - you must raise to at least the current minimum + $1. Enter the amount and click RAISE.",
      allIn: "ALL-IN",
      allInDesc: "You bet all your chips. Automatic when you raise more than you have.",
      observeOpponents: "Observe opponents' behavior - frequent raises may indicate a strong hand.",
      dontFearFold: "Don't be afraid to fold weak cards - saving chips is also a strategy.",
      positionMatters: "Position matters - playing last gives you more information.",
      manageBankroll: "Manage your bankroll - don't risk everything on one hand.",
      // Blackjack
      blackjackTitle: "Blackjack",
      blackjackDesc: "A classic card game. Collect cards worth as close to 21 as possible, but don't exceed it!",
      beatDealer: "Beat the dealer by having more points (max 21). Going over 21 = loss.",
      cardValues: "Card values",
      valuesDesc: "2-10 = face value, J/Q/K = 10 points, Ace = 1 or 11 points.",
      blackjack: "Blackjack",
    
      dealer: "Dealer",
      dealerDesc: "Dealer must hit to 16 and stand on 17+.",
      hit: "HIT",
      hitDesc: "Draw another card. Risk going over 21!",
      stand: "STAND",
      standDesc: "Keep your current total and let the dealer play.",
      double: "DOUBLE",
      doubleDesc: "Double your bet and draw exactly one card (available only at the start).",
      placeBet: "BET",
      placeBetDesc: "Set bet amount before cards are dealt.",
      alwaysDouble11: "Always double on 11 (if you can) - you can't bust.",
      standAt17: "Stand on 17+ - the risk of going over 21 is too high.",
      hitAt11Less: "Hit on 11 or less - you can't bust.",
      watchDealerCard: "Watch the dealer's up card - if it's 6 or lower, they often bust.",
      // Roulette
      rouletteTitle: "Roulette",
      rouletteDesc: "A classic casino game - bet on a number, color, or range and wait for the result!",
      predictNumber: "Predict which number the ball will land on. Winnings depend on the bet type.",
      numbers: "Numbers",
      numbersDesc: "European roulette has numbers 0-36. Zero is green, the rest are red and black.",
      payouts: "Payouts",
      payoutsDesc: "Number: 35:1 | Color: 1:1 | Even/Odd: 1:1 | Half (1-18/19-36): 1:1",
      selectChip: "Select chip",
      selectChipDesc: "Click on a chip (10, 50, 100, or 500) to select your bet value.",
      placeBetRoulette: "Place bet",
      placeBetRouletteDesc: "Click on the table where you want to bet - number, color, even, etc.",
      spin: "SPIN",
      spinDesc: "Spin the roulette wheel and wait for the result!",
      clearBets: "Clear bets",
      clearBetsDesc: "Remove all placed bets before spinning.",
      outsideBets: "Outside bets (color, even) have higher chance of winning, but lower payout.",
      multipleBeats: "You can place multiple bets at once - a strategy to cover many numbers.",
      zeroHouseEdge: "Zero gives the house an edge - avoid betting only on zero.",
      setBettingLimit: "Set a betting limit and stick to it!",
      // Slots
      slotsTitle: "Slots",
      slotsDesc: "Classic one-armed bandits - pull the lever and win!",
      lineUpSymbols: "Line up 3 matching symbols to win. Different symbols give different multipliers.",
      symbols: "Symbols",
      symbolsDesc: "🍋 Lemon (2x) | 🍒 Cherries (3x) | 🍇 Grapes (5x) | 🔔 Bell (10x) | ☘️ Clover (15x) | 7️⃣ Seven (25x) | 💎 Diamond (50x)",
      winningLines: "Winning lines",
      winningLinesDesc: "You win when 3 matching symbols appear in the middle row.",
      setBet: "Set bet",
      setBetDesc: "Use + and - buttons or enter the bet amount.",
      pull: "PULL / SPIN",
      pullDesc: "Click the lever or SPIN button to spin the reels.",
      diamondsHighest: "Diamonds give the highest payout (50x), but are the rarest.",
      sevensSecond: "Sevens are the second best symbol (25x the bet).",
      playResponsibly: "Play responsibly - slots are random, there are no 'hot' machines.",
      setLossLimit: "Set a loss limit before you start playing."
    },
    validation: {
      required: "This field is required",
      invalidEmail: "Invalid email address",
      passwordTooShort: "Password must be at least 6 characters",
      passwordMismatch: "Passwords do not match",
      amountInvalid: "Invalid amount",
      amountTooSmall: "Amount too small",
      insufficientBalance: "Insufficient balance"
    }
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'pl') ? saved : 'pl';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key; // Fallback do klucza jeśli nie znajdzie
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
