import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Tłumaczenia
const translations: Record<Language, any> = {
  pl: {
    common: {
      welcome: "Witamy",
      login: "Zaloguj się",
      register: "Zarejestruj się",
      logout: "Wyloguj",
      logOut: "Wyloguj się",
      home: "Strona główna",
      profile: "Profil",
      admin: "Panel admina",
      settings: "Ustawienia",
      language: "Język",
      balance: "Saldo",
      loading: "Ładowanie...",
      error: "Błąd",
      success: "Sukces",
      cancel: "Anuluj",
      confirm: "Potwierdź",
      back: "Wstecz",
      play: "Graj",
      bet: "Zakład",
      spin: "Zakręć",
      deal: "Rozdaj",
      hit: "Dobierz",
      stand: "Pasuj",
      double: "Podwój",
      split: "Rozdziel",
      save: "Zapisz",
      close: "Zamknij",
      deposit: "Wpłata",
      withdraw: "Wypłata",
      history: "Historia",
      characters: "znaków"
    },
    nav: {
      games: "Gry",
      slots: "Automaty",
      roulette: "Ruletka",
      blackjack: "Blackjack",
      poker: "Poker"
    },
    auth: {
      username: "Nazwa użytkownika",
      email: "Email",
      password: "Hasło",
      confirmPassword: "Potwierdź hasło",
      forgotPassword: "Zapomniałeś hasła?",
      resetPassword: "Resetuj hasło",
      noAccount: "Nie masz konta?",
      hasAccount: "Masz już konto?",
      loginSuccess: "Zalogowano pomyślnie",
      registerSuccess: "Rejestracja zakończona",
      name: "Imię",
      surname: "Nazwisko",
      signUp: "Zarejestruj się",
      enterEmail: "Wpisz email",
      enterPassword: "Wpisz hasło",
      confirmYourPassword: "Potwierdź hasło",
      invalidEmail: "Nieprawidłowy adres email",
      passwordMismatch: "Hasła się nie zgadzają",
      passwordTooShort: "Hasło musi mieć co najmniej 6 znaków",
      userExists: "Użytkownik o tym emailu już istnieje",
      invalidCredentials: "Nieprawidłowy email lub hasło",
      confirmEmail: "Potwierdź adres email przed zalogowaniem"
    },
    games: {
      blackjack: {
        title: "Blackjack",
        description: "Pobij krupiera i zdobądź 21!",
        selectMode: "Wybierz tryb gry",
        classicBlackjack: "Classic Blackjack",
        classicDescription: "Klasyczny blackjack. Graj sam przeciwko krupierowi i doskonał swoje umiejętności.",
        playSolo: "Graj Solo",
        multiplayer21: "Multiplayer 21",
        multiplayerDescription: "Prawdziwe emocje przy stole! Dołącz do innych graczy i pokonaj krupiera razem.",
        joinTable: "Dołącz do Stołu",
        singlePlayer: "Gra jednoosobowa",
        multiplayer: "Gra wieloosobowa",
        lobby: "Lobby",
        dealer: "Krupier",
        dealerScore: "Wynik krupiera",
        dealerCards: "Karty Krupiera",
        yourScore: "Twój wynik",
        betAmount: "Kwota zakładu",
        winAmount: "Wygrana",
        dealCards: "ROZDAJ KARTY",
        dealing: "ROZDAWANIE...",
        hit: "DOBIERZ",
        stand: "PASUJ",
        double: "PODWÓJ",
        win: "WYGRANA!",
        blackjack: "BLACKJACK!",
        lose: "PRZEGRANA",
        push: "REMIS",
        waiting: "Oczekiwanie...",
        dealToStart: "Rozdaj karty, aby zagrać",
        currentBet: "Stawka: {{bet}} PLN",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        gameError: "Błąd podczas rozpoczynania gry",
        hitError: "Błąd podczas dobierania karty",
        standError: "Błąd podczas pasowania",
        doubleError: "Błąd podczas podwajania",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      },
      roulettePage: {
        title: "Ruletka",
        placeBet: "Postaw zakład",
        selectNumber: "Wybierz numer",
        selectColor: "Wybierz kolor",
        red: "Czerwone",
        black: "Czarne",
        even: "Parzyste",
        odd: "Nieparzyste"
      },
      poker: {
        title: "Poker",
        description: "Zagraj w Texas Hold'em",
        selectMode: "Wybierz tryb gry",
        royalPoker: "Royal Poker",
        royalDescription: "Trening czyni mistrza. Graj przeciwko krupierowi i doskonał swoje umiejętności.",
        playSolo: "Graj Solo",
        texasHoldem: "Texas Hold'em",
        texasDescription: "Prawdziwe emocje przy stole! Dołącz do innych graczy i walcz o najwyższe stawki.",
        joinTable: "Dołącz do Stołu",
        singlePlayer: "Gra jednoosobowa",
        multiplayer: "Gra wieloosobowa",
        lobby: "Lobby",
        fold: "Pasuj",
        call: "Sprawdź",
        raise: "Podbij",
        check: "Czekaj",
        allIn: "All-in",
        yourCards: "Twoje karty",
        communityCards: "Karty wspólne",
        pot: "Pula",
        turn: "Twoja kolej",
        bet: "Zakład",
        waiting: "Oczekiwanie...",
        dealToStart: "Rozdaj karty, aby zagrać",
        dealCards: "ROZDAJ KARTY",
        dealing: "TASOWANIE...",
        nextRound: "NASTĘPNE ROZDANIE",
        selectCards: "Wybierz karty do wymiany",
        selectedCards: "Wybrano do wymiany: {{count}}",
        exchange: "WYMIEŃ KARTY",
        win: "WYGRANA!",
        lose: "PRZEGRANA",
        gameStartError: "Błąd startu",
        gameExchangeError: "Błąd wymiany",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      },
      slots: {
        title: "Automaty",
        description: "Zagraj w automaty i wygraj!",
        spin: "ZAKRĘĆ",
        bet: "Zakład",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        gameError: "Błąd podczas gry",
        win: "WYGRANA!",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      },
      roulette: {
        title: "Ruletka",
        description: "Postaw żetony i zakręć!",
        placeBet: "Postaw żeton",
        selectNumber: "Wybierz numer",
        selectColor: "Wybierz kolor",
        red: "Czerwone",
        black: "Czarne",
        even: "Parzyste",
        odd: "Nieparzyste",
        low: "Niskie",
        high: "Wysokie",
        bet: "Zakład",
        spin: "ZAKRĘĆ",
        gameError: "Błąd gry",
        win: "WYGRANA!",
        invalidBet: "Wpisz kwotę większą niż 0",
        insufficientBalance: "Niewystarczający balans",
        showLeaderboard: "Pokaż ranking",
        hideLeaderboard: "Schowaj ranking"
      }
    },
    profile: {
      title: "Twój profil",
      userInfo: "Informacje o użytkowniku",
      statistics: "Statystyki",
      gamesPlayed: "Rozegrane gry",
      totalWins: "Wygrane",
      totalLosses: "Przegrane",
      winRate: "Procent wygranych",
      missions: "Misje",
      dailyMissions: "Misje dzienne",
      dailyRewards: "Nagrody dzienne",
      streak: "Seria",
      days: "dni",
      claimReward: "Odbierz nagrodę",
      nextRewardIn: "Następna nagroda za",
      name: "Imię",
      surname: "Nazwisko",
      email: "Email",
      vipStatus: "Status VIP",
      isVip: "Tak, jestem VIP",
      notVip: "Nie jestem VIP",
      changePassword: "Zmień hasło",
      currentPassword: "Aktualne hasło",
      newPassword: "Nowe hasło",
      confirmNewPassword: "Potwierdź nowe hasło",
      security: "Bezpieczeństwo",
      changePasswordTitle: "Zmiana hasła",
      changePasswordButton: "ZMIEŃ HASŁO",
      deleteAccountButton: "USUŃ KONTO",
      deleteAccount: "Usuń konto",
      deleteAccountTitle: "Usuń konto",
      deleteAccountWarning: "⚠️ Ostrzeżenie!",
      deleteAccountText: "Ta operacja jest nieodwracalna. Wszystkie Twoje dane, historia gier i saldo zostaną permanentnie usunięte.",
      deleteAccountConfirm: "Czy na pewno chcesz usunąć swoje konto?",
      enterPasswordToConfirm: "Wpisz swoje hasło aby potwierdzić",
      allFieldsRequired: "Wszystkie pola są wymagane",
      passwordMinLength: "Nowe hasło musi mieć co najmniej 6 znaków",
      passwordNotMatching: "Nowe hasła nie są zgodne",
      passwordChangedSuccess: "Hasło zostało zmienione pomyślnie",
      passwordChanged: "Hasło zostało zmienione",
      passwordChangeError: "Nie udało się zmienić hasła",
      invalidPassword: "Nieprawidłowe hasło",
      deleteAccountError: "Nie udało się usunąć konta",
      deleteAccountSuccess: "Konto zostało pomyślnie usunięte",
      keepAccount: "Nie, zachowaj konto",
      confirmDeleteAccount: "Tak, usuń konto",
      cancel: "Anuluj",
      transactions: "Transakcje",
      gameHistory: "Historia gier",
      noTransactions: "Brak transakcji",
      noGameHistory: "Brak historii gier",
      loadMore: "Wczytaj więcej",
      depositFunds: "Wpłać środki",
      withdrawFunds: "Wypłać środki",
      enterAmount: "Wpisz kwotę",
      minimumAmount: "Minimalnie",
      maximumAmount: "Maksymalnie",
      processingPayment: "Przetwarzanie płatności...",
      balance: "Saldo",
      type: "Typ",
      outcome: "Wynik",
      winAmount: "Wygrana",
      date: "Data",
      win: "Wygrana",
      lose: "Przegrana"
    },
    missions: {
      title: "Misje",
      daily: "Dzienne",
      completed: "Ukończone",
      inProgress: "W trakcie",
      reward: "Nagroda",
      progress: "Postęp",
      claim: "Odbierz",
      claimed: "Odebrane",
      complete: "Ukończ",
      completionReward: "Nagroda za ukończenie"
    },
    admin: {
      title: "Panel Administratora",
      users: "Użytkownicy",
      userManagement: "Zarządzanie użytkownikami",
      email: "Email",
      name: "Imię",
      surname: "Nazwisko",
      balance: "Saldo",
      isVip: "VIP",
      isActive: "Aktywny",
      actions: "Akcje",
      edit: "Edytuj",
      delete: "Usuń",
      ban: "Zablokuj",
      unban: "Odblokuj",
      makeVip: "Uczyń VIP",
      removeVip: "Usuń VIP",
      noUsers: "Brak użytkowników",
      firstName: "Imię",
      lastName: "Nazwisko",
      active: "Aktywni",
      vip: "VIP",
      searchPlaceholder: "🔍 Szukaj użytkownika...",
      id: "ID",
      status: "Status",
      noPermissions: "Brak uprawnień administratora",
      serverError: "Błąd serwera",
      loading: "⏳ Ładowanie...",
      error: "❌ Błąd",
      confirmDelete: "Czy na pewno chcesz usunąć tego użytkownika?",
      userDeleted: "Użytkownik usunięty",
      deleteError: "Błąd podczas usuwania",
      updateBalance: "Zmień balans",
      enterBalance: "Podaj nowy balans:",
      balanceUpdated: "Balans zaktualizowany",
      updateError: "Błąd podczas aktualizacji balansu",
      previous: "← Poprzednia",
      next: "Następna →",
      page: "Strona",
      of: "/"
    },
    lobby: {
      title: "Lobby",
      createTable: "Utwórz stół",
      joinTable: "Dołącz do stołu",
      availableTables: "Dostępne stoły",
      tableName: "Nazwa stołu",
      minBet: "Minimalny zakład",
      maxBet: "Maksymalny zakład",
      maxPlayers: "Maks. graczy",
      currentPlayers: "Aktualnie graczy",
      waiting: "Oczekiwanie...",
      players: "Gracze",
      status: "Status",
      startGame: "Zacznij grę",
      joinGame: "Dołącz do gry",
      full: "Pełne",
      inProgress: "Trwa gra"
    },
    validation: {
      required: "To pole jest wymagane",
      invalidEmail: "Nieprawidłowy adres email",
      passwordTooShort: "Hasło musi mieć co najmniej 6 znaków",
      passwordMismatch: "Hasła się nie zgadzają",
      amountInvalid: "Nieprawidłowa kwota",
      amountTooSmall: "Kwota za mała",
      insufficientBalance: "Niewystarczające saldo"
    }
  },
  en: {
    common: {
      welcome: "Welcome",
      login: "Log in",
      register: "Sign up",
      logout: "Log out",
      logOut: "Log out",
      home: "Home",
      profile: "Profile",
      admin: "Admin panel",
      settings: "Settings",
      language: "Language",
      balance: "Balance",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      confirm: "Confirm",
      back: "Back",
      play: "Play",
      bet: "Bet",
      spin: "Spin",
      deal: "Deal",
      hit: "Hit",
      stand: "Stand",
      double: "Double",
      split: "Split",
      save: "Save",
      close: "Close",
      deposit: "Deposit",
      withdraw: "Withdraw",
      history: "History",
      characters: "characters"
    },
    nav: {
      games: "Games",
      slots: "Slots",
      roulette: "Roulette",
      blackjack: "Blackjack",
      poker: "Poker"
    },
    auth: {
      username: "Username",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      forgotPassword: "Forgot password?",
      resetPassword: "Reset password",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      loginSuccess: "Successfully logged in",
      registerSuccess: "Registration successful",
      name: "First name",
      surname: "Last name",
      signUp: "Sign up",
      enterEmail: "Enter email",
      enterPassword: "Enter password",
      confirmYourPassword: "Confirm password",
      invalidEmail: "Invalid email address",
      passwordMismatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 6 characters",
      userExists: "User with this email already exists",
      invalidCredentials: "Invalid email or password",
      confirmEmail: "Please confirm your email before logging in"
    },
    games: {
      blackjack: {
        title: "Blackjack",
        description: "Beat the dealer and get 21!",
        selectMode: "Choose game mode",
        classicBlackjack: "Classic Blackjack",
        classicDescription: "Classic blackjack. Play alone against the dealer and perfect your skills.",
        playSolo: "Play Solo",
        multiplayer21: "Multiplayer 21",
        multiplayerDescription: "Real emotions at the table! Join other players and beat the dealer together.",
        joinTable: "Join Table",
        singlePlayer: "Single player",
        multiplayer: "Multiplayer",
        lobby: "Lobby",
        dealer: "Dealer",
        dealerScore: "Dealer score",
        dealerCards: "Dealer Cards",
        yourScore: "Your score",
        betAmount: "Bet amount",
        winAmount: "Win amount",
        dealCards: "DEAL CARDS",
        dealing: "DEALING...",
        hit: "HIT",
        stand: "STAND",
        double: "DOUBLE",
        win: "WIN!",
        blackjack: "BLACKJACK!",
        lose: "LOSE",
        push: "PUSH",
        waiting: "Waiting...",
        dealToStart: "Deal cards to play",
        currentBet: "Bet: {{bet}} PLN",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        gameError: "Error starting game",
        hitError: "Error during hit",
        standError: "Error during stand",
        doubleError: "Error during double",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      },
      roulettePage: {
        title: "Roulette",
        placeBet: "Place bet",
        selectNumber: "Select number",
        selectColor: "Select color",
        red: "Red",
        black: "Black",
        even: "Even",
        odd: "Odd"
      },
      poker: {
        title: "Poker",
        description: "Play Texas Hold'em",
        selectMode: "Choose game mode",
        royalPoker: "Royal Poker",
        royalDescription: "Practice makes perfect. Play against the dealer and perfect your skills.",
        playSolo: "Play Solo",
        texasHoldem: "Texas Hold'em",
        texasDescription: "Real emotions at the table! Join other players and fight for the highest stakes.",
        joinTable: "Join Table",
        singlePlayer: "Single player",
        multiplayer: "Multiplayer",
        lobby: "Lobby",
        fold: "Fold",
        call: "Call",
        raise: "Raise",
        check: "Check",
        allIn: "All-in",
        yourCards: "Your cards",
        communityCards: "Community cards",
        pot: "Pot",
        turn: "Your turn",
        bet: "Bet",
        waiting: "Waiting...",
        dealToStart: "Deal cards to play",
        dealCards: "DEAL CARDS",
        dealing: "SHUFFLING...",
        nextRound: "NEXT ROUND",
        selectCards: "Select cards to exchange",
        selectedCards: "Selected to exchange: {{count}}",
        exchange: "EXCHANGE CARDS",
        win: "WIN!",
        lose: "LOSE",
        gameStartError: "Start error",
        gameExchangeError: "Exchange error",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      },
      slots: {
        title: "Slot Machines",
        description: "Play slots and win!",
        dealCards: "SPIN",
        bet: "Bet",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        gameError: "Game error",
        win: "WIN!",
        multiplier: "x",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      },
      roulette: {
        title: "Roulette",
        description: "Place your bets and spin!",
        placeBet: "Place bet",
        selectNumber: "Select number",
        selectColor: "Select color",
        red: "Red",
        black: "Black",
        even: "Even",
        odd: "Odd",
        low: "Low",
        high: "High",
        bet: "Bet",
        spin: "SPIN",
        gameError: "Game error",
        win: "WIN!",
        invalidBet: "Enter amount greater than 0",
        insufficientBalance: "Insufficient balance",
        showLeaderboard: "Show leaderboard",
        hideLeaderboard: "Hide leaderboard"
      }
    },
    profile: {
      title: "Your profile",
      userInfo: "User information",
      statistics: "Statistics",
      gamesPlayed: "Games played",
      totalWins: "Wins",
      totalLosses: "Losses",
      winRate: "Win rate",
      missions: "Missions",
      dailyMissions: "Daily missions",
      dailyRewards: "Daily rewards",
      streak: "Streak",
      days: "days",
      claimReward: "Claim reward",
      nextRewardIn: "Next reward in",
      name: "First name",
      surname: "Last name",
      email: "Email",
      vipStatus: "VIP Status",
      isVip: "Yes, I'm VIP",
      notVip: "Not VIP",
      changePassword: "Change password",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      security: "Security",
      changePasswordTitle: "Change password",
      changePasswordButton: "CHANGE PASSWORD",
      deleteAccountButton: "DELETE ACCOUNT",
      deleteAccount: "Delete account",
      deleteAccountTitle: "Delete account",
      deleteAccountWarning: "⚠️ Warning!",
      deleteAccountText: "This action is irreversible. All your data, game history and balance will be permanently deleted.",
      deleteAccountConfirm: "Are you sure you want to delete your account?",
      enterPasswordToConfirm: "Enter your password to confirm",
      allFieldsRequired: "All fields are required",
      passwordMinLength: "New password must be at least 6 characters",
      passwordNotMatching: "New passwords do not match",
      passwordChangedSuccess: "Password changed successfully",
      passwordChanged: "Password has been changed",
      passwordChangeError: "Failed to change password",
      invalidPassword: "Invalid password",
      deleteAccountError: "Failed to delete account",
      deleteAccountSuccess: "Account has been successfully deleted",
      keepAccount: "No, keep my account",
      confirmDeleteAccount: "Yes, delete my account",
      cancel: "Cancel",
      transactions: "Transactions",
      gameHistory: "Game history",
      noTransactions: "No transactions",
      noGameHistory: "No game history",
      loadMore: "Load more",
      depositFunds: "Deposit funds",
      withdrawFunds: "Withdraw funds",
      enterAmount: "Enter amount",
      minimumAmount: "Minimum",
      maximumAmount: "Maximum",
      processingPayment: "Processing payment...",
      balance: "Balance",
      type: "Type",
      outcome: "Outcome",
      winAmount: "Win amount",
      date: "Date",
      win: "Win",
      lose: "Lose"
    },
    missions: {
      title: "Missions",
      daily: "Daily",
      completed: "Completed",
      inProgress: "In progress",
      reward: "Reward",
      progress: "Progress",
      claim: "Claim",
      claimed: "Claimed",
      complete: "Complete",
      completionReward: "Completion reward"
    },
    admin: {
      title: "Admin Panel",
      users: "Users",
      userManagement: "User Management",
      email: "Email",
      name: "First name",
      surname: "Last name",
      balance: "Balance",
      isVip: "VIP",
      firstName: "First name",
      lastName: "Last name",
      active: "Active",
      vip: "VIP",
      searchPlaceholder: "🔍 Search user...",
      id: "ID",
      status: "Status",
      noPermissions: "Admin permissions required",
      serverError: "Server error",
      loading: "⏳ Loading...",
      error: "❌ Error",
      confirmDelete: "Are you sure you want to delete this user?",
      userDeleted: "User deleted",
      deleteError: "Error while deleting user",
      updateBalance: "Change balance",
      enterBalance: "Enter new balance:",
      balanceUpdated: "Balance updated",
      updateError: "Error while updating balance",
      previous: "← Previous",
      next: "Next →",
      page: "Page",
      of: "/"
    },
    lobby: {
      title: "Lobby",
      createTable: "Create table",
      joinTable: "Join table",
      availableTables: "Available tables",
      tableName: "Table name",
      minBet: "Minimum bet",
      maxBet: "Maximum bet",
      maxPlayers: "Max players",
      currentPlayers: "Current players",
      waiting: "Waiting...",
      players: "Players",
      status: "Status",
      startGame: "Start game",
      joinGame: "Join game",
      full: "Full",
      inProgress: "In progress"
    },
    validation: {
      required: "This field is required",
      invalidEmail: "Invalid email address",
      passwordTooShort: "Password must be at least 6 characters",
      passwordMismatch: "Passwords do not match",
      amountInvalid: "Invalid amount",
      amountTooSmall: "Amount too small",
      insufficientBalance: "Insufficient balance"
    }
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'pl') ? saved : 'pl';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key; // Fallback do klucza jeśli nie znajdzie
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
